version: '3.8'

services:
  backend:
    build: ./backend
    container_name: vpn_backend
    restart: always

    ports:
      - "8080:8080"

    volumes:
      - ./db/config:/app/db/config

    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/db/config/vpn_db.sqlite
      SPRING_DATASOURCE_USERNAME: ""
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  bot:
    build: ./bot
    container_name: vpn_bot
    restart: always

    depends_on:
      - backend

    environment:
      BACKEND_URL: http://backend:8080