spring.datasource.url=jdbc:mysql://localhost:3306/vpn_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=vpnuser
spring.datasource.password=vpnpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver